### ISSUE TITLE
shuts off

### ISSUE THREAD

**Issue by c0debreaker** [kpwn/tpwn#1]
Didn't get a root shell on my 10.10.2 but it shutdown my mac. Sweet :)

**Comment by kpwn** [comment]
Do you have SMAP? It effectively mitigates this bug.

**Comment by c0debreaker** [comment]
Most likely I don't have it because I'm not sure what SMAP is. Btw, I just patched my Yosemite to 10.10.5 and also installed SUIDGuardNG. Will it effectively prevent this bug?

**Comment by kpwn** [comment]
SMAP is a CPU feature. You _could_ have it if you have a last-gen. SUIDGuardNG shouldn't even make your mac crash but just kill tpwn before it can do any harm. you should probably update SUIDGuardNG, since the anti-tpwn has been added just today. If you can, please install NULLGuard alongside it, since I've heard rumors of a possible SUIDGuardNG anti-tpwn bypass. Issue 1 in NULLGuard explains what to do to install it.

**Comment by c0debreaker** [comment]
I checked tpwn using ps ax but I didn't see any process. I will update my SUIDGuardNG but not sure where to find the latest update. The one in github is not updated, maybe i have a different github source. I will also intall NULLGuard
